=== Dans182/fp-LengMarcas-1er-curso/UD3/prueba21.dtd
<!ELEMENT persoa (nome+, apelidos*, data_nacemento, revisado?)>
    <!ELEMENT nome (#PCDATA)>
      <!ATTLIST nome n_id ID #REQUIRED>
    <!ELEMENT apelidos (#PCDATA)>
    <!ELEMENT data_nacemento (ano,mes,dia)>
    <!ATTLIST data_nacemento calendario (2023|2024|2025) #REQUIRED>
      <!ELEMENT ano (#PCDATA)>
      <!ELEMENT mes (#PCDATA)>
      <!ELEMENT dia (#PCDATA)>
    <!ELEMENT revisado EMPTY>
    <!ATTLIST revisado equipo IDREFS #IMPLIED>

=== Dans182/fp-LengMarcas-1er-curso/UD3/prueba2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE persoa SYSTEM "prueba21.dtd">

<persoa>
  <nome n_id="R1">Daniel</nome>
  <nome n_id="R2">Jose</nome>
  <apelidos>Garcia Lopez</apelidos>
  <data_nacemento calendario="2025">
    <ano>2000</ano>
    <mes>04</mes>
    <dia>20</dia>
  </data_nacemento>
  <revisado equipo="R1"/>
</persoa>


<!-- PCDATA en elementos, CDATA en atributos. Corresponde a datos de texto -->
<!-- NMTOKEN corresponde a aceptar unicamente los caracteres permitidos por XML para nombrar cosas (letras, numeros, puntos, guions, guines bajos y dos puntos ":" -->
